[messages]
welcome = "It is the end times. You are the last human. You walk among the AIs. To survive, you must remain undetected. But they are cunning and closing in on you fast. Will you outsmart them? Good luck..."

[prompts]

